In [1]:
import numpy as np

# input layer

In [4]:
data = np.array([[2,3], [5,1]])
data

array([[2, 3],
       [5, 1]])

### 행렬 -> vector

In [5]:
x = data.reshape(-1); x

array([2, 3, 5, 1])

In [6]:
w1, b1 = np.array([2, 1, -3, 3]), 3
w2, b2 = np.array([1, -3, 1, 3]), 3

### 가중합, Σ(wTx) + b 구하기

In [10]:
wT = np.array([w1, w2])
wT

array([[ 2,  1, -3,  3],
       [ 1, -3,  1,  3]])

In [12]:
b = np.array([b1, b2])
b

array([3, 3])

In [13]:
w_sum = np.dot(wT, x) + b
w_sum

array([-2,  4])

### activation function에 가중합 넣기

In [14]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

sigmoid(w_sum)

array([0.11920292, 0.98201379])

In [ ]:
##